[workspace]
members = [
    "git-function-history-lib",
    "cargo-function-history",
    "git-function-history-gui",
    "function_history_backend_thread",
    "git_function_history-proc-macro",
    "function-grep",
]
resolver = "2"
