[package]
name = "git_function_history"
version = "0.7.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/mendelsshop/git_function_history/tree/main/git-function-history-lib"
keywords = ["git_function_history", "git", "function", ]
categories = ["tools", "git"]
description = "show function history from git"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["parallel", "cache"]
parallel = ["dep:rayon", "git-features/parallel"]
# c_lang = []
# unstable = ["dep:gosyn", "dep:javaparser"]
unstable = ["dep:gosyn"]
cache = ["dep:cached"]

[dependencies]
chrono = "0.4.23"
ra_ap_syntax = "0.0.144"
rayon = { version = "1.6.1", optional = true }
# rustpython-parser = "0.1.2"
# for end_lines but can't be publsihed b/c git depenency
rustpython-parser = { features = ["lalrpop"], git = "https://github.com/RustPython/RustPython.git", rev = "c01f014b1269eedcf4bdb45d5fbc62ae2beecf31" }
lib-ruby-parser = "3.0.12"
gosyn = {version = "0.2.0", optional = true}
# can't be published b/c git dependency
# javaparser = {git = "https://github.com/tanin47/javaparser.rs", optional = true}
cfg-if = "1.0.0"
cached = {version = "0.41.0", optional = true}
gitoxide-core = "0.21.0"
git-repository = { version = "0.30.0", default-features = false, features = ["max-performance-safe"] }
git-features = { version = "0.25.0", features = ["zlib", "once_cell"] }