[package]
name = "git_function_history"
version = "0.6.2"
edition = "2021"
license = "MIT"
repository = "https://github.com/mendelsshop/git_function_history/tree/main/git-function-history-lib"
keywords = ["git_function_history", "git", "function", ]
categories = ["tools", "git"]
description = "show function history from git"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["parallel"]
parallel = ["dep:rayon"]
c_lang = []

[dependencies]
chrono = "0.4.22"
ra_ap_syntax = "0.0.133"
rayon = { version = "1.5.1", optional = true }
rustpython-parser = "0.1.2"
