[package]
name = "cargo-function-history"
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/mendelsshop/git_function_history/tree/main/cargo-function-history"
keywords = ["git_function_history", "git", "function", ]
categories = ["tools", "git", "tui"]
description = "cargo frontend for git-function-history"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git_function_history = { path = "../git-function-history-lib", version = "0.5.4" }
lazy_static = "1.3.0"
tui = { version = "0.19", features = ["crossterm"], default-features = false }
crossterm = "0.25.0"
tokio = { version = "1", features = ["full"] }
eyre = "0.6"