[package]
name = "function-grep"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.2", features = ["derive"] }
tree-sitter = "0.20.10"
tree-sitter-c = "0.20.8"
tree-sitter-python = "0.20.4"
tree-sitter-rust = "0.20.4"
