[package]
name = "git-function-history-gui"
version = "0.3.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/mendelsshop/git_function_history/tree/main/git-function-history-gui"
keywords = ["git_function_history", "git", "function", ]
categories = ["tools", "git", "gui" ]
description = "GUI frontend for git-function-history"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = {version = "0.19.0", features = ["dark-light"]}
git_function_history = { path = "../git-function-history-lib", version = "0.5.4" }
function_history_backend_thread = { path = "../function_history_backend_thread", version = "0.1.0"}
