on: 
  push:
  workflow_dispatch:
name: Clippy check + test for the lib
jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          rustup component add clippy
          cd ..
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features -p git_function_history
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup rust
        uses: dtolnay/rust-toolchain@stable
      - name: test
        run: |
          cd ..
          cargo test -p git_function_history -- --nocapture