on: 
  push:
  workflow_dispatch:
name: Clippy check + test for the lib
jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          
          rustup toolchain install nightly
          rustup +nightly component add clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          toolchain: nightly
          args: -p git_function_history --features unstable, c_lang 
  nightly-clang-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          override: true
      - name: test
        run: |
          cargo +nightly test -p git_function_history --features unstable, c_lang -- --nocapture

  test-clang: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup rust
        uses: dtolnay/rust-toolchain@stable
      - name: test
        run: |
          cargo test -p git_function_history --features c_lang -- --nocapture

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup rust
        uses: dtolnay/rust-toolchain@stable
      - name: test
        run: |
          cargo test -p git_function_history -- --nocapture

  test-nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          override: true
      - name: test
        run: |
          cargo +nightly test -p git_function_history --features unstable -- --nocapture