on:
  release:
    types: [published, released, prereleased]
    branches:
      - main
  workflow_dispatch:

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup rust
        uses: dtolnay/rust-toolchain@stable
      - run: |
          cargo publish -p git_function_history --token ${{ secrets.CRATES_TOKEN }} 
          cargo publish -p git-function-history-gui --token ${{ secrets.CRATES_TOKEN }}
          cargo publish -p cargo-function-history --token ${{ secrets.CRATES_TOKEN }} 