name: release all to crates.io

on:
  release:
    types: [published, released, prereleased]
    branches:
      - main
  workflow_dispatch:

jobs:
  Publish:
    runs-on: ubuntu-latest
    strategy:    
      matrix:
        crate: [git_function_history, git-function-history-gui, cargo-function-history, function_history_backend_thread, git_function_history_proc-macro]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: setup rust
        uses: dtolnay/rust-toolchain@stable
      - run: |
          cargo publish -p ${{ matrix.crate }} --token ${{ secrets.CRATES_TOKEN }} 