name: update loc every 6 hours
on:
  schedule:
    # every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  update_loc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update loc
      - run: |
          sudo apt-get install tokei
      - name: install python
        uses: actions/setup-python@v2
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pygithub
          python -m pip install json
      - name: run script
        run: |
          python stats/check_loc.py ${{ secrets.GITHUB_TOKEN }}
  update_downloads:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install python
        uses: actions/setup-python@v2
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pygithub
          python -m pip install json
          python -m pip install requests
          python -m pip install toml
      - name: run script
        run: |
          python stats/check_downloads.py ${{ secrets.GITHUB_TOKEN }}




  

